name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - stable/**

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v2
      - run: nix flake show --all-systems
      - run: nix flake check --no-build

  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v2
      - run: nix fmt -- --fail-on-change

  build:
    runs-on: ${{ matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        system: [x86_64-linux, aarch64-linux]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v2
      - run: |
          for pkg in $(nix eval --json '#.packages.x86_64-linux' | jq -r 'keys[]'); do
            echo "::group::$pkg"
            nix build --print-build-logs ".#packages.${{ matrix.system }}.$pkg"
            echo "::endgroup::"
          done
